### PR TITLE
Update to master

### PR DESCRIPTION
**Pull request by deads2k**
`git merge -X theirs upstream/master`

And then ran `make` to see it work.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Gave this a read through, seems like a reasonable set of changes to bring in.

Just wondering if we can quickly run this build against the openshift/api repo to check for any diffs it's going to make before we merge it

**Comment by JoelSpeed** [comment]
After some learning about the toolchain in the API repo (so much make), I managed to run the controller-gen from this branch against the API repo.

The diff created reformatted a bunch of descriptions (seems they're handling whitespace better now) and added `x-kubernetes-map-type: atomic` to the properties of a bunch of our CRDs. I assume we've been tagging things with the map type for some time but not actually been seeing it within the API schema. Not entirely sure what the effect of that on existing APIs will be

**Comment by deads2k** [comment]
> After some learning about the toolchain in the API repo (so much make), I managed to run the controller-gen from this branch against the API repo.
> 
> The diff created reformatted a bunch of descriptions (seems they're handling whitespace better now) and added `x-kubernetes-map-type: atomic` to the properties of a bunch of our CRDs. I assume we've been tagging things with the map type for some time but not actually been seeing it within the API schema. Not entirely sure what the effect of that on existing APIs will be

Did we get our generator using the latest here?

**Comment by JoelSpeed** [comment]
The generator is now updated to latest in the api repo so we can go ahead and merge this

**Pull request merged**
